### ISSUE TITLE
Adding a slider

### ISSUE THREAD

**Issue by vilav** [rbartoli/threesixty#2]
Hello,

this is probably the most performant 360 slider out there (2 KB!).
Is there a way to connect a range slider to it?
So in addition to swiping on the image itself, a user could move the range slider to manipulate the 360? 

Thanks!

**Comment by rbartoli** [comment]
Hi @vilav,

Sorry for the late reply and thanks for using the component and for the good feedback. I hope you've been already able to sort this issue, but in case you haven't...

The functionality you're asking for is not built-in by default, however it should be not too complicated to implement: my suggestion will be to create and expose a `setCurrentFrame` method that you can call directly from your slider change event, passing the frame number that has to be set inside the threesixty component. The `setCurrentFrame` action will have to set the currentFrame variable with the value you're passing in, and it will have to call the `replaceImage` function to update the image itself.

I hope this helps!
