### ISSUE TITLE
Mobile devices issue

### ISSUE THREAD

**Issue by dpeychev** [rbartoli/threesixty#3]
Hi there,

i used this plugin in reactjs project. When i test it in responsive mode for mobile devices, the slider not works when i try to slide between images. I get this error in console:

index.js:78 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
drag @ index.js:78

`
  var drag = function drag(e) {
    e.preventDefault();
`

Do you have some idea about that?

Regards

**Comment by rbartoli** [comment]
Hi @dpeychev,

Sorry for the late reply. I think what you're getting is just a warning, so it will not affect what you're developing.

I'm going to release an updated library ASAP with a fix addressing the addEventListener change in Chrome.

**Comment by rbartoli** [comment]
Hi @dpeychev,

I've just released a new package that addresses the issue in Chrome.

Thanks,

Riccardo
